<a href="https://colab.research.google.com/github/Hkd225/Framingham-Heart-Study/blob/main/Framingham_Heart_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os
import kagglehub
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib
path = kagglehub.dataset_download("noeyislearning/framingham-heart-study")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/noeyislearning/framingham-heart-study?dataset_version_number=1...

100%|██████████| 58.1k/58.1k [00:00<00:00, 44.4MB/s]

Extracting files...

In [2]:
df = pd.read_csv(os.path.join(path, 'framingham_heart_study.csv'))

In [3]:
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [4]:
df.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4240.000000,4240.000000,4135.000000,4240.000000,4211.000000,4187.000000,4240.000000,4240.000000,4240.000000,4190.000000,4240.000000,4240.000000,4221.000000,4239.000000,3852.000000,4240.000000
mean,0.429245,49.580189,1.979444,0.494104,9.005937,0.029615,0.005896,0.310613,0.025708,236.699523,132.354599,82.897759,25.800801,75.878981,81.963655,0.151887
std,0.495027,8.572942,1.019791,0.500024,11.922462,0.169544,0.076569,0.462799,0.158280,44.591284,22.033300,11.910394,4.079840,12.025348,23.954335,0.358953
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,90.000000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [7]:
from sklearn.model_selection import train_test_split


X = df.drop('TenYearCHD', axis=1)
y = df['TenYearCHD']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train = X_train.copy()
X_test = X_test.copy()

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train[X_train.columns] = scaler.fit_transform(X_train)
X_test[X_test.columns] = scaler.transform(X_test)

In [9]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

imputer = SimpleImputer(strategy='median')
X_train_clean = imputer.fit_transform(X_train)
X_test_clean = imputer.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(random_state=42, eval_metric='logloss'),
    "SVM": SVC(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "Naive Bayes": GaussianNB(),
    "MLP Neural Network": MLPClassifier(max_iter=1000, random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train_clean, y_train)
    y_pred = model.predict(X_test_clean)
    accuracy = accuracy_score(y_test, y_pred)
    results.append({"Model": name, "Accuracy": accuracy})

df_results = pd.DataFrame(results).sort_values(by='Accuracy', ascending=False).reset_index(drop=True)
print(df_results)

                 Model  Accuracy
0             AdaBoost  0.850236
1        Random Forest  0.847877
2                  SVM  0.846698
3  Logistic Regression  0.844340
4    Gradient Boosting  0.840802
5                  KNN  0.831368
6   MLP Neural Network  0.824292
7              XGBoost  0.823113
8          Naive Bayes  0.805425
9        Decision Tree  0.747642

In [13]:
import joblib
import pandas as pd

top_3_models = df_results['Model'].head(9).tolist()

for model_name in top_3_models:
    joblib.dump(models[model_name], f"{model_name.replace(' ', '_')}.pkl")

joblib.dump(scaler, 'scaler.pkl')
joblib.dump(imputer, 'imputer.pkl')

data_baru = pd.DataFrame({
    'male': [1, 0, 1, 0, 0],
    'age': [39, 46, 48, 61, 46],
    'education': [4.0, 2.0, 1.0, 3.0, 2.0],
    'currentSmoker': [0, 0, 1, 1, 1],
    'cigsPerDay': [0.0, 0.0, 20.0, 30.0, 23.0],
    'BPMeds': [0.0, 0.0, 0.0, 0.0, 0.0],
    'prevalentStroke': [0, 0, 0, 0, 0],
    'prevalentHyp': [0, 0, 0, 1, 0],
    'diabetes': [0, 0, 0, 0, 0],
    'totChol': [195.0, 250.0, 245.0, 225.0, 285.0],
    'sysBP': [106.0, 121.0, 127.5, 150.0, 130.0],
    'diaBP': [70.0, 81.0, 80.0, 95.0, 84.0],
    'BMI': [26.97, 28.73, 25.34, 28.58, 23.1],
    'heartRate': [80.0, 95.0, 75.0, 65.0, 85.0],
    'glucose': [77.0, 76.0, 70.0, 103.0, 85.0]
})

data_baru_scaled = scaler.transform(data_baru)
data_baru_clean = imputer.transform(data_baru_scaled)

for model_name in top_3_models:
    loaded_model = joblib.load(f"{model_name.replace(' ', '_')}.pkl")
    prediksi = loaded_model.predict(data_baru_clean)
    print(f"Prediksi {model_name}:\n{prediksi}\n")

Prediksi AdaBoost:
[0 0 0 0 0]

Prediksi Random Forest:
[0 0 0 1 0]

Prediksi SVM:
[0 0 0 0 0]

Prediksi Logistic Regression:
[0 0 0 0 0]

Prediksi Gradient Boosting:
[0 0 0 0 0]

Prediksi KNN:
[0 0 0 1 0]

Prediksi MLP Neural Network:
[0 0 0 1 0]

Prediksi XGBoost:
[0 0 0 1 0]

Prediksi Naive Bayes:
[0 0 0 0 0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(